FROM python:3.10-slim

# Install dependencies for Buildozer
RUN apt-get update && \
    apt-get install -y \
    git \
    zip \
    unzip \
    openjdk-8-jdk \
    python3-pip \
    python3-setuptools \
    python3-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    libsqlite3-dev \
    curl \
    wget && \
    pip install --upgrade pip && \
    pip install buildozer cython

WORKDIR /home/build