name: Build Android APK (Buildozer Docker)

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for buildozer
        run: docker build -f Dockerfile.buildozer -t kivy-buildozer:latest .

      - name: Run build container to make APK
        run: |
          CONTAINER_ID=$(docker run -d --name buildozer_run kivy-buildozer:latest tail -f /dev/null)
          docker exec $CONTAINER_ID bash -lc "cd /home/build && buildozer -v android debug"
          docker cp $CONTAINER_ID:/home/build/bin ./bin || true
          docker rm -f $CONTAINER_ID

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
